### ISSUE TITLE
AdaKerja Submission Review

### ISSUE THREAD

**Issue by IrfaanDzakiy** [mdarud/facebook-birthday-bot#1]
Hi Daru. I'm Irfaan, engineer from AdaKerja. First of all thank you for your submission.

Before i review your submission further, can you please improve the readme file or steps on how to test using the demo app, as I cannot find a way to run and test your app.

Thanks!

**Comment by mdarud** [comment]
Hi Irfaan, thank you for your feedback and I'm sorry for the inconvenience, I didn't have the permission from Facebook to open the project for public, so, I have included the tester account in the README.md file. 

Thank you!

**Comment by IrfaanDzakiy** [comment]
Daru, the bot is stuck on asking name

![image](https://user-images.githubusercontent.com/52844931/187393019-043f60c2-7ea1-4d72-99ab-771a6884f4aa.png)

**Comment by mdarud** [comment]
Hello, I'm sorry, it seems there was a problem when connecting to the database, I already fixed it. Please try again. Thank you so much!
